import Search from "./Search";
import Grouping from "./Grouping";
import { Fragment } from "react";
import NavBar from "../Home/Header/NavBar";
import Head from "next/head";
import { Container } from "@mui/material";
import { useRouter } from "next/router";
import { useSelector } from "react-redux";
import Fixed from "../Fixed";


const Show_Cart = () => {
  const router = useRouter();
  const { search } = router.query;
  const { product, cart } = useSelector((state) => state);

  return (
    <Fragment>
      <Head>
        <title> نسیم | ثبت سفارش</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Container maxWidth="xl">
        <Search reSearch={search} product={product} cart={cart} />/
        <Grouping product={product} cart={cart} />
      </Container>
      <Fixed />
    </Fragment>
  );
};

export default Show_Cart;
